services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    container_name: microservice_catalog
    restart: always
    environment:
      - GIN_MODE=$GIN_MODE
      - APP_PORT=$APP_PORT
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=$DB_DATABASE
    env_file:
      - .env
    volumes:
      - .:/go/src/app
      - ~/.air:/root/.air
    depends_on:
      - postgres_db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:latest
    container_name: support_gateway
    restart: always
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - app
    networks:
      - app-network

  postgres_db:
    image: postgres:16
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_DATABASE
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      app-network:
        aliases:
          - pgsql

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
